### ISSUE TITLE
Review 3: TESTS

### ISSUE THREAD

**Issue by ltetrel** [harveyaa/nixtract-slurm#7]
[TESTS](../blob/master/tests/tests.py)
1. ModuleNotFoundError: No module named 'natsort'
2. test_no_reg_files test_with_reg_files test_one_completed test_two_batches fails (nixtract not installed)

**Comment by harveyaa** [comment]
I added natsort to the requirements, and the nixtract installation issues are sorted now that it is up on pypi.
