### ISSUE TITLE
Review 4: SLURM parameters

### ISSUE THREAD

**Issue by ltetrel** [harveyaa/nixtract-slurm#8]
[SLURM parameters](https://github.com/harveyaa/nixtract-slurm/blob/a4347d5ef575e204475403097dca83d26b9e99f1/nslurm/nslurm.py#L165-L166)
1. You should scale the memory based on the number of files (not fixed 1G). Indeed the number of files a job process is not the same (memory consumption different for n_files<1000; <10000; <inf). 
2. Same comment for the time

**Comment by harveyaa** [comment]
The reason I fixed the memory at 1G (if it isn't specified) is from doing tests of the memory usage with different number of subjects from ADHD200 and ABIDE, the memory usage was stable around 500MB regardless of the number of subjects as the script basically processes a subject writes the output to file and then frees up the memory. It could definitely use more extensive tests with large datasets though to see how it behaves then and set the memory accordingly. 
The time does scale with n subjects, right now it's about 10s per subject (depending a bit on which batch).
